version: '3'

services:
  postgres:
    build: ./postgres
    ports:
      - 6543:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust

#  keycloak:
#    image: jboss/keycloak:15.0.2
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#    environment:
#      DB_VENDOR: "POSTGRES"
#      DB_ADDR: postgres
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: root
#      KEYCLOAK_USER: brooks
#      KEYCLOAK_PASSWORD: Cepwan-muxbex-6pijmo

  camunda:
    build: ./car-rental
    depends_on:
      - postgres
    ports:
      - 8070:8070
