spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/process_engine
#    url: jdbc:postgresql://localhost:6543/process_engine
    username: postgres
    password: root

server:
  port: 8070

# All authorization is disabled for the purposes of the workshop.
# The code below is a basic configuration setup for enabling authorization in a way that only
# the External Clients of the Camunda applications can connect to an engine using the camunda-realm in keycloak.

#camunda:
#  bpm:
#    authorization:
#      enabled: true
#    auto-deployment-enabled: true
#    deployment-resource-pattern:
#      - classpath:*.bpmn

#plugin.identity.keycloak:
#  keycloakIssuerUrl: http://localhost:8080/auth/realms/camunda <-- provided there is a camunda realm in keycloak.
#  keycloakAdminUrl: http://localhost:8080/auth/admin/realms/camunda
#  clientId: camunda-identity-service
#  clientSecret: [secret]
#  useUsernameAsCamundaUserId: true
#  administratorGroupName: camunda-admins
